name: ngrinder
services:
  controller:
    image: ngrinder/controller:3.5.9-p1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8300:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent:3.5.9-p1
    platform: linux/amd64
    restart: unless-stopped
    links:
      - controller